config/routes.rb
Rails.application.routes.draw do



  # Это правило говорит: если пользователь заходит по адресу /,
  # направь его в контроллер users, действие index
  # Грубо говоря, на главной странице у нас список юзеров
  root 'users#index'

  # ресурс пользователей (экшен destroy не поддерживается)
  resources :users, except: [:destroy]

  # ресурс сессий (только три экшена :new, :create, :destroy)
  resources :sessions, only: [:new, :create, :destroy]

  # ресурс вопросов (кроме экшенов :show, :new, :index)
  resources :questions, except: [:show, :new, :index]


  #  синонимы путей - в дополнение к созданным в ресурсах выше
  get 'sign_up' => 'users#new'
  get 'log_out' => 'sessions#destroy'
  get 'log_in' => 'sessions#new'
end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :user

  validates :text, :user, presence: true



  # ХХХ
  # демонтрация жизненного цикла объекта
  # навесили на все популярные коллбэки свои методы
  before_validation :before_validation
  after_validation :after_validation
  before_save :before_save
  before_create :before_create
  after_create :after_create
  after_save :after_save


  before_update :before_update
  after_update :after_update

  before_destroy :before_destroy
  after_destroy :after_destroy

  private

  # динамически сгенерируем пару методов для каждого действия,
  # используя возможности руби
  ['validation', 'save', 'create', 'update', 'destroy'].each do |action|
    ['before', 'after'].each do |time|
      define_method("#{time}_#{action}") do
        puts "******> #{time} #{action}"
      end
    end
  end



end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, except: [:create]


  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to user_path(@question.user), notice: 'Вопрос задан'
    else
      render :edit
    end
  end

  # PATCH/PUT /questions/1
  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Вопрос сохранен'
    else
      render :edit
    end
  end

  # DELETE /questions/1
  def destroy
    user = @question.user
    @question.destroy
    redirect_to user_path(@question.user), notice: 'Вопрос удален'
  end

  private
  def authorize_user
    reject_user unless @question.user == current_user
  end

    # Use callbacks to share common setup or constraints between actions.
    def load_question
      @question = Question.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def question_params
      # защита от уязвимости -- пользователь может менять ответы только у собственных вопросов
      if current_user.present? && params[:question][:user_id].to_i == current_user.id
        params.require(:question).permit(:user_id, :text, :answer)
      else
        params.require(:question).permit(:user_id, :text)
      end
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<!-- Форма для создания/правки вопроса -->

<div class="form">
  <!-- Форма для объекта @question -->
  <%= form_for(@question) do |f| %>
      <% if @question.errors.any? %>
          <div class="form-errors">
            <ul>
              <% @question.errors.full_messages.each do |message| %>
                  <li class="form-error-message"><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <!-- Скрытое поле - айдишник юзера, кому задается вопрос -->
      <%= f.hidden_field :user_id %>

      <div class="form-field">
        <%= f.label :text, 'Вопрос', class: 'form-label' %>
        <%= f.text_area :text, class: 'form-textarea' %>
      </div>


      <!-- Простая авторизация - может ли текущий юзер править вопрос? -->
      <% if current_user.present? && current_user == @question.user %>
          <div class="form-field">
            <%= f.label :answer, 'Ответ', class: 'form-label' %>
            <%= f.text_area :answer, class: 'form-textarea' %>
          </div>
      <% end %>

      <div class="form-action buffer-both">
        <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
        или
        <%= link_to "вернуться", user_path(@question.user) %>
      </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<%# Это фрагмет (паршал, partial) для вывода вопроса %>
<%# В нем определена локальная переменная question, в которую при вызове %>
<%# будет передан как в метод ruby объект после ключа (object: @question) %>

<!-- Локальная переменная этого паршиала -->
<% question ||= nil %>
<!-- Определяем какая будет иконка -->
<% action_icon = question.answer.blank? ? 'reply' : 'pencil' %>


<div class="question">
  <div class="question-content">
    <div class="question-text text-lead">
      <%= question.text %>
    </div>

    <!-- Если вопрос имеет ответ, показать его -->
    <% if question.answer.present? %>
        <div class="question-answer text-lead">
          <%= question.answer %>
        </div>
    <% end %>

    <div class="question-date">
      <!-- Локализованный вывод даты вопроса в коротком формате -->
      <%= l(question.created_at, format: :short) %>
    </div>
  </div>

  <!-- Простая авторизация: только владелец вопроса может его редактировать -->
  <% if question.user == current_user %>
      <div class="question-actions">
        <%= link_to fa_icon(action_icon), edit_question_path(question) %>
        <%= link_to fa_icon('trash-o'), question_path(question),
                    method: :delete, data: {confirm: 'Точно удалить вопрос?'} %>
      </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<!-- Страница редактирования вопроса -->
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Вопрос</h1>

  <div class="column-1-2">
    <!-- Подключаем паршиал form -->
    <%= render 'form' %>
  </div>
</div>