config/routes.rb
Rails.application.routes.draw do



  # Это правило говорит: если пользователь заходит по адресу /,
  # направь его в контроллер users, действие index
  # Грубо говоря, на главной странице у нас список юзеров
  root 'users#index'

  # ресурс пользователей (экшен destroy не поддерживается)
  resources :users, except: [:destroy]

  # ресурс сессий (только три экшена :new, :create, :destroy)
  resources :sessions, only: [:new, :create, :destroy]

  # ресурс вопросов (кроме экшенов :show, :new, :index)
  resources :questions, except: [:show, :new, :index]


  #  синонимы путей - в дополнение к созданным в ресурсах выше
  get 'sign_up' => 'users#new'
  get 'log_out' => 'sessions#destroy'
  get 'log_in' => 'sessions#new'
end

app/views/layouts/application.html.erb
<%#Это макет для всех страниц нашего сайта%>
<!DOCTYPE html>
<html>
<%#Именно он определяет, что будет в теге head каждой нашей html-страницы%>
<head>
  <meta charset="UTF-8"/>
  <%#Именно здесь мы подключаем все стили и прописываем один (в рамках обучения)%>
  <%#тег title для всех страниц сайта%>
  <title>Хорошие вопросы</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
  <div class="container">
    <div class="header-logo">
      <%#Ссылка на главную страницу сайта root_path%>
      <h1 class="header-title"><%= link_to "Хорошие вопросы", root_path %></h1>
    </div>

    <div class="header-nav">
      <!-- Если есть текущий юзер (значит он залогинен) -->
      <% if current_user %>
          <!-- Даем ссылки на его профиль и на логаут -->
          <%= link_to "@#{current_user.username}", user_path(current_user) %> |
          <%= link_to 'Выйти', log_out_path %>
      <% else %>
          <!-- Если нету - ссылки на регистрацию и логин -->
          <%= link_to 'Зарегистрироваться', sign_up_path, class: 'button button-light button-small' %>
          <%= link_to 'Войти', log_in_path, class: 'button button-light button-small' %>
      <% end %>

    </div>
  </div>
</div>

<div class="content">
  <div class="container">

    <!-- Если в объеккте flash есть что-то, выводим содержимое на страницу -->
    <% if flash.any? %>
        <div class="content-wrapper buffer-both">
          <% flash.each do |name, message| %>
              <%= content_tag :div, message, class: "flash-#{name}" %>
          <% end %>
        </div>
    <% end %>

    <% # Вместо волшебной конструкции yield рельсы подставят то, что срендерит %>
    <% # шаблон для нужной нам страницы, например, users/show %>
    <%= yield %>
  </div>
</div>


</body>
</html>